Refactor
kellervmarcelo/compilers pull request #7
Opened 2022-03-14 13:19 UTC by arthurbpf

re-write of some parts of the program to make it easier to extend it in the future

2022-03-18 22:27 UTC, kellervmarcelo requested changes

2022-03-18 22:27 UTC, kellervmarcelo commented on src/lexical_analysis.py
> +        try:
Acho que se pah é melhor manter no arquivo do utils pra manter o mais abstraído possível caso a gente precise usar em algum outro lugar

2022-03-18 22:27 UTC, kellervmarcelo commented on src/lexical_analysis.py
> +
Ele pediu pra ser um dicionário (❁´◡`❁)

2022-03-25 23:06 UTC, arthurbpf commented on compiler.py
> +    print(check_word(token))
Sim

2022-03-25 23:07 UTC, arthurbpf commented on src/lexical_analysis.py
> +
resorvemo

2022-03-25 23:13 UTC, merged